//
//  Document.swift
//  Pinterest
//
//  Created by Anastasia Demidova on 12.03.2021.
//

import Foundation

class Document {
    let description: [String : String] =
        ["Gerbera" : """
    Gerbera is a genus of plants in the Asteraceae. It was named in honour of German botanist and medical doctor Traugott Gerber who travelled extensively in Russia and was a friend of Carl Linnaeus.
    Gerbera is native to tropical regions of South America, Africa and Asia. The first scientific description of a Gerbera was made by J.D. Hooker in Curtis's Botanical Magazine in 1889 when he described Gerbera jamesonii, a South African species also known as Transvaal daisy or Barberton daisy. Gerbera is also commonly known as the African daisy.
    Gerbera species bear a large capitulum with striking, two-lipped ray florets in yellow, orange, white, pink or red colours. The capitulum, which has the appearance of a single flower, is actually composed of hundreds of individual flowers. The morphology of the flowers varies depending on their position in the capitulum. The flower heads can be as small as 7 cm in diameter or up to 12 cm.
    Gerbera is very popular and widely used as a decorative garden plant or as cut flowers. The domesticated cultivars are mostly a result of a cross between Gerbera jamesonii and another South African species Gerbera viridifolia. The cross is known as Gerbera hybrida. Thousands of cultivars exist. They vary greatly in shape and size. Colours include white, yellow, orange, red, and pink. The centre of the flower is sometimes black. Often the same flower can have petals of several different colours.
    Gerbera is also important commercially. It is the fifth most used cut flower in the world (after rose, carnation, chrysanthemum, and tulip). It is also used as a model organism in studying flower formation.
    Gerbera contains naturally occurring coumarin derivatives. Gerbera is a tender perennial plant. It is attractive to bees, butterflies, and birds, but resistant to deer. Small ones are called gerbrinis.
    """, "Cactus" : """
        A cactus is a member of the plant family Cactaceae, a family comprising about 127 genera with some 1750 known species of the order Caryophyllales. The word "cactus" derives, through Latin, from the Ancient Greek κάκτος, kaktos, a name originally used by Theophrastus for a spiny plant whose identity is now not certain. Cacti occur in a wide range of shapes and sizes. Most cacti live in habitats subject to at least some drought. Many live in extremely dry environments, even being found in the Atacama Desert, one of the driest places on earth. Cacti show many adaptations to conserve water. Almost all cacti are succulents, meaning they have thickened, fleshy parts adapted to store water. Unlike many other succulents, the stem is the only part of most cacti where this vital process takes place. Most species of cacti have lost true leaves, retaining only spines, which are highly modified leaves. As well as defending against herbivores, spines help prevent water loss by reducing air flow close to the cactus and providing some shade. In the absence of leaves, enlarged stems carry out photosynthesis. Cacti are native to the Americas, ranging from Patagonia in the south to parts of western Canada in the north—except for Rhipsalis baccifera, which also grows in Africa and Sri Lanka.
        Cactus spines are produced from specialized structures called areoles, a kind of highly reduced branch. Areoles are an identifying feature of cacti. As well as spines, areoles give rise to flowers, which are usually tubular and multipetaled. Many cacti have short growing seasons and long dormancies, and are able to react quickly to any rainfall, helped by an extensive but relatively shallow root system that quickly absorbs any water reaching the ground surface. Cactus stems are often ribbed or fluted, which allows them to expand and contract easily for quick water absorption after rain, followed by long drought periods. Like other succulent plants, most cacti employ a special mechanism called "crassulacean acid metabolism" (CAM) as part of photosynthesis. Transpiration, during which carbon dioxide enters the plant and water escapes, does not take place during the day at the same time as photosynthesis, but instead occurs at night. The plant stores the carbon dioxide it takes in as malic acid, retaining it until daylight returns, and only then using it in photosynthesis. Because transpiration takes place during the cooler, more humid night hours, water loss is significantly reduced.
        Many smaller cacti have globe-shaped stems, combining the highest possible volume for water storage, with the lowest possible surface area for water loss from transpiration. The tallest free-standing cactus is Pachycereus pringlei, with a maximum recorded height of 19.2 m (63 ft), and the smallest is Blossfeldia liliputiana, only about 1 cm (0.4 in) in diameter at maturity. A fully grown saguaro (Carnegiea gigantea) is said to be able to absorb as much as 200 U.S. gallons (760 l; 170 imp gal) of water during a rainstorm. A few species differ significantly in appearance from most of the family. At least superficially, plants of the genus Pereskia resemble other trees and shrubs growing around them. They have persistent leaves, and when older, bark-covered stems. Their areoles identify them as cacti, and in spite of their appearance, they, too, have many adaptations for water conservation. Pereskia is considered close to the ancestral species from which all cacti evolved. In tropical regions, other cacti grow as forest climbers and epiphytes (plants that grow on trees). Their stems are typically flattened, almost leaf-like in appearance, with fewer or even no spines, such as the well-known Christmas cactus or Thanksgiving cactus (in the genus Schlumbergera).
        Cacti have a variety of uses: many species are used as ornamental plants, others are grown for fodder or forage, and others for food (particularly their fruit). Cochineal is the product of an insect that lives on some cacti.
        Many succulent plants in both the Old and New World – such as some Euphorbiaceae (euphorbias) – bear a striking resemblance to cacti, and may incorrectly be called "cactus" in common usage.
        """, "Marguerite" : """
        Garden marguerites, also known as marguerite daisies, are cultivars of plants in the subtribe Glebionidinae of the family Asteraceae, the great majority being hybrids created in cultivation. One of the genera belonging to the subtribe, Argyranthemum, was introduced into cultivation from the Canary Islands in the 18th century, and modern cultivars are mostly sold and grown under the genus name Argyranthemum or athe species name Argyranthemum frutescens, although many are actually intergeneric hybrids. The first such hybrids involved species now placed in the genus Glebionis, but other crosses within the subtribe are known. Breeding has aimed at introducing flower heads in varied colours and shapes while retaining the shrubby habit of Argyranthemum. Garden marguerites are used as summer bedding or grown in containers. Most are only half-hardy. They can be trained into shapes such as pyramids or grown as standards.
        Garden marguerites are derived from wild species in the family Asteraceae. They have the typical inflorescences of the family, in which what may appear to be a single flower is actually a composite flower head composed of many individual flowers or florets. Small tightly packed florets make up the central disc, which is surrounded by florets with longer petals (ligules), making up the rays of the complete flower head. In wild Argyranthemum species, which form the basis of garden marguerites, the flower heads have yellow centres and usually white rays, although A. maderense has pale yellow rays. Modern cultivars have much more varied flower colours and shapes. The central disc may remain yellow, be of the same colour as the ray florets, or be of a different colour. The central disc florets are enlarged in some cultivars. In fully double flower heads, the disk florets have longer petals like the ray florets. The cultivar 'Supa594' (Summersong White) has flower heads in which no central disc is visible, as all florets have ray-like petals.
        """, "Chrysanthemum" : """
        Chrysanthemums sometimes called mums or chrysanths, are flowering plants of the genus Chrysanthemum in the family Asteraceae. They are native to East Asia and northeastern Europe. Most species originate from East Asia and the center of diversity is in China.Countless horticultural varieties and cultivars exist.
        The genus once included more species, but was split several decades ago into several genera, putting the economically important florist's chrysanthemums in the genus Dendranthema. The naming of these genera has been contentious, but a ruling of the International Botanical Congress in 1999 changed the defining species of the genus to Chrysanthemum indicum, restoring the florist's chrysanthemums to the genus Chrysanthemum.
        Genera now separated from Chrysanthemum include Argyranthemum, Glebionis, Leucanthemopsis, Leucanthemum, Rhodanthemum, and Tanacetum.
        Historical painting of chrysanthemums from the New International Encyclopedia, 1902
        Wild Chrysanthemum taxa are herbaceous perennial plants or subshrubs. They have alternately arranged leaves divided into leaflets with toothed or occasionally smooth edges. The compound inflorescence is an array of several flower heads, or sometimes a solitary head. The head has a base covered in layers of phyllaries. The simple row of ray florets is white, yellow, or red; many horticultural specimens have been bred to bear many rows of ray florets in a great variety of colors. The disc florets of wild taxa are yellow. Pollen grains are appropriately 34 microns. The fruit is a ribbed achene. Chrysanthemums start blooming early in the autumn. This is also known as the favorite flower for the month of November.
        """, "Stitchwort" : """
        Greater stitchwort grows in woodland and along roadside verges, hedgerows and grassy banks. It has many other common names, including 'wedding cakes', 'Star-of-Bethlehem', 'daddy's-shirt-buttons' and 'Snapdragon' - the latter because its stems are brittle and easily break. Its pretty, star-shaped, white flowers bloom from April to June; as the seed capsules ripen, they can be heard 'popping' in late spring. Greater stitchwort has five white petals, each deeply notched and almost divided into two. Its green leaves are grass-like in appearance and its brittle stems are square. Greater stitchwort has larger flowers (2-3cm across) than its relative, Lesser stitchwort (0.5-1cm across).
        """, "Rose" : """
        A rose is a woody perennial flowering plant of the genus Rosa, in the family Rosaceae, or the flower it bears. There are over three hundred species and tens of thousands of cultivars.They form a group of plants that can be erect shrubs, climbing, or trailing, with stems that are often armed with sharp prickles. Flowers vary in size and shape and are usually large and showy, in colours ranging from white through yellows and reds. Most species are native to Asia, with smaller numbers native to Europe, North America, and northwestern Africa. Species, cultivars and hybrids are all widely grown for their beauty and often are fragrant. Roses have acquired cultural significance in many societies. Rose plants range in size from compact, miniature roses, to climbers that can reach seven meters in height. Different species hybridize easily, and this has been used in the development of the wide range of garden roses.
        Rose thorns are actually prickles – outgrowths of the epidermis
        Longitudinal section through a developing rose hip
        The leaves are borne alternately on the stem. In most species they are 5 to 15 centimetres (2.0 to 5.9 in) long, pinnate, with (3–) 5–9 (–13) leaflets and basal stipules; the leaflets usually have a serrated margin, and often a few small prickles on the underside of the stem. Most roses are deciduous but a few (particularly from Southeast Asia) are evergreen or nearly so.
        The flowers of most species have five petals, with the exception of Rosa sericea, which usually has only four. Each petal is divided into two distinct lobes and is usually white or pink, though in a few species yellow or red. Beneath the petals are five sepals (or in the case of some Rosa sericea, four). These may be long enough to be visible when viewed from above and appear as green points alternating with the rounded petals. There are multiple superior ovaries that develop into achenes. Roses are insect-pollinated in nature.
        The aggregate fruit of the rose is a berry-like structure called a rose hip. Many of the domestic cultivars do not produce hips, as the flowers are so tightly petalled that they do not provide access for pollination. The hips of most species are red, but a few (e.g. Rosa pimpinellifolia) have dark purple to black hips. Each hip comprises an outer fleshy layer, the hypanthium, which contains 5–160 "seeds" (technically dry single-seeded fruits called achenes) embedded in a matrix of fine, but stiff, hairs. Rose hips of some species, especially the dog rose (Rosa canina) and rugosa rose (Rosa rugosa), are very rich in vitamin C, among the richest sources of any plant. The hips are eaten by fruit-eating birds such as thrushes and waxwings, which then disperse the seeds in their droppings. Some birds, particularly finches, also eat the seeds.
        The sharp growths along a rose stem, though commonly called "thorns", are technically prickles, outgrowths of the epidermis (the outer layer of tissue of the stem), unlike true thorns, which are modified stems. Rose prickles are typically sickle-shaped hooks, which aid the rose in hanging onto other vegetation when growing over it. Some species such as Rosa rugosa and Rosa pimpinellifolia have densely packed straight prickles, probably an adaptation to reduce browsing by animals, but also possibly an adaptation to trap wind-blown sand and so reduce erosion and protect their roots (both of these species grow naturally on coastal sand dunes). Despite the presence of prickles, roses are frequently browsed by deer. A few species of roses have only vestigial prickles that have no points.
        About 50 million years ago, the first rose in the Americas were found in modern-day Colorado. Today's garden roses come from 18th-century China. Among the old Chinese garden roses, the Old Blush group is the most primitive, while newer groups are the most diverse.
        """, "Lily" : """
        Lilium (members of which are true lilies) is a genus of herbaceous flowering plants growing from bulbs, all with large prominent flowers. Lilies are a group of flowering plants which are important in culture and literature in much of the world. Most species are native to the temperate northern hemisphere, though their range extends into the northern subtropics. Many other plants have "lily" in their common name but are not related to true lilies.
        Lilies are tall perennials ranging in height from 2–6 ft (60–180 cm). They form naked or tunicless scaly underground bulbs which are their organs of perennation. In some North American species the base of the bulb develops into rhizomes, on which numerous small bulbs are found. Some species develop stolons. Most bulbs are buried deep in the ground, but a few species form bulbs near the soil surface. Many species form stem-roots. With these, the bulb grows naturally at some depth in the soil, and each year the new stem puts out adventitious roots above the bulb as it emerges from the soil. These roots are in addition to the basal roots that develop at the base of the bulb.
        The flowers are large, often fragrant, and come in a wide range of colors including whites, yellows, oranges, pinks, reds and purples. Markings include spots and brush strokes. The plants are late spring- or summer-flowering. Flowers are borne in racemes or umbels at the tip of the stem, with six tepals spreading or reflexed, to give flowers varying from funnel shape to a "Turk's cap". The tepals are free from each other, and bear a nectary at the base of each flower. The ovary is 'superior', borne above the point of attachment of the anthers. The fruit
        Seeds ripen in late summer. They exhibit varying and sometimes complex germination patterns, many adapted to cool temperate climates.
        Naturally most cool temperate species are deciduous and dormant in winter in their native environment. But a few species which distribute in hot summer and mild winter area (Lilium candidum, Lilium catesbaei, Lilium longiflorum) lose leaves and remain relatively short dormant in Summer or Autumn, sprout from Autumn to winter, forming dwarf stem bearing a basal rosette of leaves until, after they have received sufficient chilling, the stem begins to elongate in warming weather.
        """, "Tulip" : """
        Tulips (Tulipa) form a genus of spring-blooming perennial herbaceous bulbiferous geophytes (having bulbs as storage organs). The flowers are usually large, showy and brightly colored, generally red, pink, yellow, or white (usually in warm colors). They often have a different colored blotch at the base of the tepals (petals and sepals, collectively), internally. Because of a degree of variability within the populations, and a long history of cultivation, classification has been complex and controversial. The tulip is a member of the lily family, Liliaceae, along with 14 other genera, where it is most closely related to Amana, Erythronium and Gagea in the tribe Lilieae. There are about 75 species, and these are divided among four subgenera. The name "tulip" is thought to be derived from a Persian word for turban, which it may have been thought to resemble. Tulips originally were found in a band stretching from Southern Europe to Central Asia, but since the seventeenth century have become widely naturalised and cultivated (see map). In their natural state they are adapted to steppes and mountainous areas with temperate climates. Flowering in the spring, they become dormant in the summer once the flowers and leaves die back, emerging above ground as a shoot from the underground bulb in early spring.
        Originally growing wild in the valleys of the Tian Shan Mountains, tulips were cultivated in Constantinople as early as 1055. By the 15th century, tulips were among the most prized flowers; becoming the symbol of the Ottomans. While tulips had probably been cultivated in Persia from the tenth century, they did not come to the attention of the West until the sixteenth century, when Western diplomats to the Ottoman court observed and reported on them. They were rapidly introduced into Europe and became a frenzied commodity during Tulip mania. Tulips were frequently depicted in Dutch Golden Age paintings, and have become associated with the Netherlands, the major producer for world markets, ever since. In the seventeenth century Netherlands, during the time of the Tulip mania, an infection of tulip bulbs by the tulip breaking virus created variegated patterns in the tulip flowers that were much admired and valued. While truly broken tulips do not exist anymore, the closest available specimens today are part of the group known as the Rembrandts – so named because Rembrandt painted some of the most admired breaks of his time.
        Breeding programs have produced thousands of hybrid and cultivars in addition to the original species (known in horticulture as botanical tulips). They are popular throughout the world, both as ornamental garden plants and as cut flowers.
        """, "Peony" : """
        The peony or paeony is a flowering plant in the genus Paeonia, the only genus in the family Paeoniaceae. Peonies are native to Asia, Europe and Western North America. Scientists differ on the number of species that can be distinguished, ranging from 25 to 40, although the current consensus is 33 known species. The relationships between the species need to be further clarified. Most are herbaceous perennial plants 0.25–1 metre (1–3 ft) tall, but some are woody shrubs 0.25–3.5 metres (1–11 ft) tall. They have compound, deeply lobed leaves and large, often fragrant flowers, in colors ranging from purple and pink to red, white or yellow, in late spring and early summer. The flowers have a short blooming season, usually only 7–10 days. Peonies are popular garden plants in temperate regions.Herbaceous peonies are also sold as cut flowers on a large scale, although generally only available in late spring and early summer.
        """, "Cornflower" : """
        Centaurea cyanus, commonly known as cornflower or bachelor's button,is an annual flowering plant in the family Asteraceae native to Europe. In the past, it often grew as a weed in cornfields (in the broad sense of "corn", referring to grains, such as wheat, barley, rye, or oats), hence its name. It is now endangered in its native habitat by agricultural intensification, particularly by over-use of herbicides. However, Centaurea cyanus is now also naturalised in many other parts of the world, including North America and parts of Australia through introduction as an ornamental plant in gardens and as a seed contaminant in crop seeds. Centaurea cyanus is an annual plant growing to 40–90 cm tall, with grey-green branched stems. The leaves are lanceolate and 1–4 cm long. The flowers are most commonly an intense blue colour and arranged in flowerheads (capitula) of 1.5–3 cm diameter, with a ring of a few large, spreading ray florets surrounding a central cluster of disc florets. The blue pigment is protocyanin, which in roses is red.Fruits are approx. 3.5 mm long with 2-3 mm long pappus bristles.It flowers all summer.
        """, "Susen" : """
        The sunflower (Helianthus annuus) is a living annual plant in the family Asteraceae, with a large flower head (capitulum). The stem of the flower can grow up to 3 metres tall, with a flower head that can be 30 cm wide. Other types of sunflowers include the California Royal Sunflower, which has a burgundy (red + purple) flower head.
        The flower head is actually an inflorescence made of hundreds or thousands of tiny flowers called florets. The central florets look like the centre of a normal flower, apseudanthium. The benefit to the plant is that it is very easily seen by the insects and birds which pollinate it, and it produces thousands of seeds.
        The sunflower is the state flower of Kansas. That is why Kansas is sometimes called the Sunflower State. To grow well, sunflowers need full sun. They grow best in fertile, wet, well-drained soil with a lot of mulch. In commercial planting, seeds are planted 45 cm (1.5 ft) apart and 2.5 cm (1 in) deep.
        Head displaying florets in spirals of 34 and 55 around the outside
        The outer petal-bearing florets are the sterile florets and can be yellow, red, orange, or other colors. The florets inside the circular head are called disc florets, which mature into seeds.
        The flower petals within the sunflower's cluster are always in a spiral pattern. Generally, each floret is oriented toward the next by approximately the golden angle, 137.5°, producing a pattern of interconnecting spirals, where the number of left spirals and the number of right spirals are successive Fibonacci numbers. Typically, there are 34 spirals in one direction and 55 in the other; on a very large sunflower there could be 89 in one direction and 144 in the other.
        Sunflowers commonly grow to heights between 1.5 and 3.5 m (5–12 ft.). The tallest sunflower confirmed by Guinness World Records is 9.17 m (2014, Germany). In 16th century Europe the record was already 7.3 m (24 ft., Spain). Most cultivars are variants of H. annuus, but four other species (all perennials) are also domesticated. This includes H. tuberosus, the Jerusalem Artichoke, which produces edible tubers.
        """, "Lavender" : """
        Lavandula (common name lavender) is a genus of 47 known species of flowering plants in the mint family, Lamiaceae. It is native to the Old World and is found in Cape Verde and the Canary Islands, and from Europe across to northern and eastern Africa, the Mediterranean, southwest Asia to southeast India. Many members of the genus are cultivated extensively in temperate climates as ornamental plants for garden and landscape use, for use as culinary herbs, and also commercially for the extraction of essential oils. The most widely cultivated species, Lavandula angustifolia, is often referred to as lavender, and there is a color named for the shade of the flowers of this species. Despite its use over centuries in traditional medicine and cosmetics, there is no high-quality clinical evidence that lavender has any effects on diseases or improves health.
        """, "Lilic" : """
        Syringa (lilac) is a genus of 12 currently recognized species of flowering woody plants in the olive family (Oleaceae), native to woodland and scrub from southeastern Europe to eastern Asia, and widely and commonly cultivated in temperate areas elsewhere.
        The genus is most closely related to Ligustrum (privet), classified with it in Oleaceae tribus Oleeae subtribus Ligustrinae.
        Lilacs are used as food plants by the larvae of some moth species, including copper underwing, scalloped oak and Svensson's copper underwing.
        """, "Sunflower" : """
        The sunflower (Helianthus annuus) is a living annual plant in the family Asteraceae, with a large flower head (capitulum). The stem of the flower can grow up to 3 metres tall, with a flower head that can be 30 cm wide. Other types of sunflowers include the California Royal Sunflower, which has a burgundy (red + purple) flower head.
        The flower head is actually an inflorescence made of hundreds or thousands of tiny flowers called florets. The central florets look like the centre of a normal flower, apseudanthium. The benefit to the plant is that it is very easily seen by the insects and birds which pollinate it, and it produces thousands of seeds.
        The sunflower is the state flower of Kansas. That is why Kansas is sometimes called the Sunflower State. To grow well, sunflowers need full sun. They grow best in fertile, wet, well-drained soil with a lot of mulch. In commercial planting, seeds are planted 45 cm (1.5 ft) apart and 2.5 cm (1 in) deep.
        Head displaying florets in spirals of 34 and 55 around the outside
        The outer petal-bearing florets are the sterile florets and can be yellow, red, orange, or other colors. The florets inside the circular head are called disc florets, which mature into seeds.
        The flower petals within the sunflower's cluster are always in a spiral pattern. Generally, each floret is oriented toward the next by approximately the golden angle, 137.5°, producing a pattern of interconnecting spirals, where the number of left spirals and the number of right spirals are successive Fibonacci numbers. Typically, there are 34 spirals in one direction and 55 in the other; on a very large sunflower there could be 89 in one direction and 144 in the other.
        Sunflowers commonly grow to heights between 1.5 and 3.5 m (5–12 ft.). The tallest sunflower confirmed by Guinness World Records is 9.17 m (2014, Germany). In 16th century Europe the record was already 7.3 m (24 ft., Spain). Most cultivars are variants of H. annuus, but four other species (all perennials) are also domesticated. This includes H. tuberosus, the Jerusalem Artichoke, which produces edible tubers.
        """, "Chamomile": """
        Chamomile (American English) or camomile (British English; see spelling differences) is the common name for several daisy-like plants of the family Asteraceae. Two of the species are commonly used to make herbal infusions for traditional medicine, and there is some evidence that chamomile has an effect on health. The word "chamomile" derived via French and Latin from Greek, "earth apple", from χαμαί (khamai) "on the ground" and "apple". First used in the 13th century, the spelling "chamomile" corresponds to the Latin chamomilla and Greek chamaimelon. The spelling "camomile" is a British derivation from the French.
        """]
}
